# Append these two services to /opt/netbet/docker-compose.yml before the final "volumes:" section.
# Then run: cd /opt/netbet && docker compose up -d --build risk-analytics-ui-api risk-analytics-ui-web

  risk-analytics-ui-api:
    build:
      context: ./risk-analytics-ui/api
      dockerfile: Dockerfile
    container_name: risk-analytics-ui-api
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB:-netbet}
      POSTGRES_USER: ${POSTGRES_USER:-netbet}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-netbet}
    ports:
      - "8000:8000"

  risk-analytics-ui-web:
    build:
      context: ./risk-analytics-ui/web
      dockerfile: Dockerfile
    container_name: risk-analytics-ui-web
    restart: unless-stopped
    depends_on:
      - risk-analytics-ui-api
    ports:
      - "3000:80"
